### ISSUE TITLE
部分steam商品下的mods无法下载，

### ISSUE THREAD

**Issue by NingMeiWang** [Virace/steam-workshop-download#1]
![6S(Y F86`6(D`PR24Q9BWQI](https://user-images.githubusercontent.com/62290592/77375657-1d7f3d00-6da9-11ea-9cf8-db1ce9642a1f.png)

应该怎么解决呢？
如https://steamcommunity.com/sharedfiles/filedetails/?id=1242187210&searchtext=
![2K9~J)T_2M841X4IDY4JB](https://user-images.githubusercontent.com/62290592/77375805-8d8dc300-6da9-11ea-8a20-cf818a9f7c38.png)

**Comment by Virace** [comment]
这类网站很多的 https://steamworkshopdownloader.io/
